# Generated by Django 4.1.5 on 2023-01-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('middle_name', models.CharField(blank=True, max_length=40, null=True)),
                ('last_name', models.CharField(max_length=40)),
                ('profile_photo', models.ImageField(blank=True, upload_to='teacherImgs')),
                ('introduction_video', models.FileField(blank=True, upload_to='teacherIntroVid')),
                ('certificates', models.FileField(blank=True, upload_to='certificates')),
                ('description', models.TextField()),
                ('teacher_nationality', models.CharField(max_length=40)),
                ('teacher_review', models.TextField()),
            ],
        ),
    ]
