# Generated by Django 4.1.5 on 2023-01-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='teacher_stars',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5),
        ),
    ]
