# Generated by Django 4.1.5 on 2023-01-22 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classdata', '0004_students_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='studentImgs'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='teacher_nationality',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='classdata.students')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='classdata.teachers')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
