# Generated by Django 4.1.5 on 2023-01-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classdata', '0005_alter_students_profile_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='teacher',
            field=models.ManyToManyField(related_name='teacher', to='classdata.teachers'),
        ),
    ]
