# Generated by Django 4.1.5 on 2023-01-22 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classdata', '0008_alter_teachers_teacher_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='teacher_stars',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5),
        ),
    ]
