# Generated by Django 4.1.5 on 2023-01-22 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classdata', '0009_alter_teachers_teacher_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='teacher_stars',
            field=models.IntegerField(choices=[(5, '5'), (4, '4'), (3, '3'), (2, '2'), (1, '1')], default=5),
        ),
    ]
