# Generated by Django 4.1.5 on 2023-01-22 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classdata', '0011_alter_students_after_lesson_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='teacher',
        ),
        migrations.AddField(
            model_name='students',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher', to='classdata.teachers'),
        ),
    ]
