# Generated by Django 4.1.5 on 2023-01-22 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classdata', '0013_remove_students_teacher_students_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='student',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='students',
            name='teacher',
            field=models.ManyToManyField(related_name='teachers', to='classdata.teachers'),
        ),
    ]
