# Generated by Django 4.1.5 on 2023-01-22 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classdata', '0014_remove_lessons_student_remove_lessons_teacher_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='teacher',
            new_name='teachers',
        ),
    ]
